---
title: "Acoustic Networks"
output: html_document
date: "2026-02-04"
---

```{r}
library(dplyr)
library(tidyverse)
library(tidygraph)
library(ggraph)
library(viridis)
library(ggforce)
library(igraph)
library(geosphere)
library(lubridate)
library(ggOceanMaps)
library(ggplot2)
library(sf)
library(terra)
```

```{r}
df <- read.csv("./cleaned_detections.csv") %>%
  mutate(Date = as.Date(Date, format = "%m/%d/%y"))

juvenile_taglist = c(
  '50185', '50196', '62273', '62266', '55576',
  '50184','62272', '55578', '50198', '50193', '50168', '50195', '50173', '50199', '50177',
  '55561','55560','55564','55562','55563','62277','62268','58082','58084','58090','58095',
  '58097','58099','58088','58092')

df_det <- df %>% # filter to only juvenile tags
  separate(Transmitter, into = c("x", "y", "Transmitter_ID"), sep = "-") %>%
  filter(Transmitter_ID %in% juvenile_taglist) %>% 
  select(DateTime, Date, Transmitter_ID, Lat, Lon, Site.Name) # select only relevant columns

df_mb <- df_det %>% # filter to only detections in MB
  filter(Lat > 36.599577 & Lat < 37.0) 
```


```{r}
# fill in site groups
df_mb <- df_mb %>%
  mutate(
    Site.GroupName = case_when(
      Site.Name %in% c("Cement Ship", "SC3", "SC4", "SC2", "Aptos Swim Buoy") ~ "Santa Cruz",
      Site.Name %in% c("HMS OA1", "Breakwater", "Lovers Pt", "MY1", "MY3", "MY4", "SWC1", "Bird Rock") ~ "Monterey",
      Site.Name %in% c("MSB1", "Salinas River State Beach") ~ "Marina",
      Site.Name %in% c("ML2", "ML3", "ML4") ~ "Moss Landing",
      Site.Name %in% c("Manresa State Beach") ~ "Manresa",
      TRUE ~ NA_character_)) %>% 
  filter(!is.na(Site.GroupName))
```

# Network Analysis 
```{r fig.height=5, fig.width=7, dpi=150}
# simple abacus 
colormap <- c(
  "Santa Cruz"  = "#961E3E",  # maroon
  "Manresa"     = "#4C8BB5",  # blue
  "Moss Landing"= "#FA865C",  # orange
  "Marina"      = "#1D7562",  # forest green
  "Monterey"    = "#B35BB2"   # purple
)
df_bay <- df_mb %>% 
  filter(Site.GroupName %in% c("Monterey", "Marina", "Moss Landing", 
         "Manresa", "Santa Cruz"))

df_bay$Site.GroupName = factor(df_bay$Site.GroupName, levels = names(colormap))

# plot
ggplot(df_bay, aes(x = Date, y = Transmitter_ID, fill = Site.GroupName)) +
  geom_point(shape = 21, size = 3, color = "black", stroke = 0.2, alpha = 0.8) +
  scale_fill_manual(values = colormap, 
                    breaks = names(colormap)) +
  labs(x = "",
    y = "White Shark Acoustic Transmitter ID",
    title = "Acoustic Detections - Monterey Bay", fill = "Site Group") +
  theme_bw() +
  theme(
    legend.position="right",
    panel.grid = element_blank()) + scale_x_date( 
                                      labels = scales::label_date_short(), date_breaks = "3 month")
```

```{r}
edges_raw <- df_mb %>%
  select(-Site.Name) %>%
  group_by(Transmitter_ID) %>%
  mutate(
    from_site = Site.GroupName,
    to_site   = lead(Site.GroupName),
    from_time = DateTime,
    to_time   = lead(DateTime),
    dt_days   = as.numeric(difftime(to_time, from_time, units = "days")),
    month     = month(Date)) %>%
  ungroup() %>%
  filter(
    !is.na(to_site),
    from_site != to_site,
    dt_days <= 7)

sites <- tibble::tribble(
  ~Site.GroupName, ~lon,    ~lat,
  "Santa Cruz",    -121.949, 36.969,
  "Manresa",       -121.83, 36.90,
  "Moss Landing",  -121.79, 36.80,
  "Marina",        -121.80, 36.68,
  "Monterey",      -121.89, 36.60
)

edges_yearly <- edges_raw %>%
  mutate(year = lubridate::year(from_time)) %>%
  group_by(year, from_site, to_site) %>%
  summarise(
    n_transitions = n(),
    n_sharks = n_distinct(Transmitter_ID),
    .groups = "drop"
  ) %>%
  left_join(sites, by = c("from_site" = "Site.GroupName")) %>%
  rename(from_lon = lon, from_lat = lat) %>%
  left_join(sites, by = c("to_site" = "Site.GroupName")) %>%
  rename(to_lon = lon, to_lat = lat)

nodes_yearly <- df_mb %>%
  mutate(year = lubridate::year(DateTime)) %>%
  group_by(year, Site.GroupName) %>%
  summarise(
    n_detections = n(),
    n_sharks = n_distinct(Transmitter_ID),
    .groups = "drop"
  ) %>%
  left_join(sites, by = "Site.GroupName")
```

```{r, fig.width=10, fig.height=8, dpi=150}
# create per-shark edge list 
edges_shark_yearly <- edges_raw %>%
  mutate(year = lubridate::year(from_time)) %>%
  left_join(sites, by = c("from_site" = "Site.GroupName")) %>%
  rename(from_lon = lon, from_lat = lat) %>%
  left_join(sites, by = c("to_site" = "Site.GroupName")) %>%
  rename(to_lon = lon, to_lat = lat)

shark_year_summary <- edges_shark_yearly %>%
  group_by(Transmitter_ID, year) %>%
  summarise(
    first_edge_date = min(Date),
    last_edge_date  = max(Date),
    n_edges         = n(),
    .groups = "drop"
  ) %>% 
  mutate(duration = (last_edge_date - first_edge_date) + 1,
         frequency = n_edges/as.numeric(duration))

shark_year_summary %>% 
  group_by(year) %>% 
  summarize(mean_edge_per_d = mean(frequency), 
            n = n(), sd = sd(frequency))

edges_shark_yearly %>%
  mutate(
    # non-directional pair (alphabetical order)
    from_to_pair = pmap_chr(
      list(from_site, to_site),
      ~ paste(sort(c(..1, ..2)), collapse = "-")
    ),
    # direction based on latitude
    direction = ifelse(to_lat > from_lat, "North", "South"), 
    dummydate = as.Date(paste0("2000-", format(Date, "%m-%d"))),
  ) %>% 
  ggplot(aes(x = dummydate, y = from_to_pair, color = direction)) +
  geom_point(size = 2) +
  facet_wrap(~year(Date), scales = "free_y") +
  theme_bw() +
  scale_x_date(
    limits = as.Date(c("2000-01-01", "2000-12-31")),
    date_breaks = "1 month",
    date_labels = "%b"
  ) +
  labs(
    x = "Date",
    y = "Site pair",
    color = "Direction"
  )

```


```{r}
bbox <- c(
  xmin = -122.2,
  xmax = -121.7,
  ymin = 36.5,
  ymax = 37.0
)

plot_yearly_network <- function(year_i,
                                edges_yearly,
                                nodes_yearly,
                                bbox) {

  edges_y <- edges_yearly %>% dplyr::filter(year == year_i)
  nodes_y <- nodes_yearly %>% dplyr::filter(year == year_i)

  p <- basemap(
    data = data.frame(
      lon = c(bbox["xmin"], bbox["xmax"]),
      lat = c(bbox["ymin"], bbox["ymax"])
    ),
    bathymetry = TRUE,
    expand.factor = 1.1,
    bathy.style = "rcb"
  )

  ## undirected, weighted edges
  p <- p +
    geom_segment(
      data = edges_y,
      aes(
        x = from_lon, y = from_lat,
        xend = to_lon, yend = to_lat,
        linewidth = n_transitions
      ),
      color = "steelblue",
      alpha = 0.8
    ) +
    scale_linewidth(range = c(1, 6), name = "Transitions")

  ## nodes
  p <- p +
    geom_point(
      data = nodes_y,
      aes(x = lon, y = lat, size = n_sharks),
      shape = 21,
      fill = "red",
      color = "black",
      stroke = 0.4,
      alpha = 0.85
    ) +
    scale_size_continuous(
      name = "Sharks detected",
      range = c(2, 10)
    )

  p +
    labs(
      title = paste(year_i),
      x = NULL,
      y = NULL
    ) +
    theme_minimal() + guides(fill = "none")
}

plot_site_reference_map <- function(sites, bbox) {

  p <- basemap(
    data = data.frame(
      lon = c(bbox["xmin"], bbox["xmax"]),
      lat = c(bbox["ymin"], bbox["ymax"])
    ),
    bathymetry = TRUE,
    expand.factor = 1.1,
    bathy.style = "rcb"
  )

  # Add points
  p <- p +
    geom_point(
      data = sites,
      aes(x = lon, y = lat),
      shape = 21,
      fill = "red",
      color = "black",
      size = 3,
      stroke = 0.5
    )

  # Add labels
  p <- p +
    geom_text(
      data = sites,
      aes(x = lon, y = lat, label = Site.GroupName),
      nudge_y = 0.01,
      size = 5,
      fontface = "bold"
    )

  p +
    labs(
      title = "Site Reference Map",
      x = NULL,
      y = NULL
    ) +
    theme_minimal()
}

```


```{r fig.height=6, fig.width=6, dpi=150}
p2022 <- plot_yearly_network(2022, edges_yearly, nodes_yearly, bbox)
p2023 <- plot_yearly_network(2023, edges_yearly, nodes_yearly, bbox)
p2024 <- plot_yearly_network(2024, edges_yearly, nodes_yearly, bbox)
p2025 <- plot_yearly_network(2025, edges_yearly, nodes_yearly, bbox)

p2022
p2023
p2024
p2025
plot_site_reference_map(sites, bbox)
```

```{r}
# node useage

region_availability <- tibble( # region availability (receiver coverage)
  Site.GroupName = c("Santa Cruz", "Moss Landing", "Monterey", "Manresa", "Marina"),
  available_2022 = c(1, 1, 1, 0, 0),
  available_2023 = c(1, 1, 1, 0, 0),
  available_2024 = c(1, 1, 1, 1, 1),
  available_2025 = c(1, 0.25, 1, 0, 1) # moss landing data not yet downloaded
) %>%
  pivot_longer(
    cols = starts_with("available_"),
    names_to = "year",
    values_to = "available"
  ) %>%
  mutate(
    year = as.integer(sub("available_", "", year))
  )

regions_used <- nodes_yearly %>%
  mutate(year = as.integer(year)) %>%
  group_by(year) %>%
  summarise(
    regions_used = n_distinct(Site.GroupName),
    .groups = "drop"
  )

regions_available <- region_availability %>%
  group_by(year) %>%
  summarise(
    regions_available = sum(available),
    .groups = "drop"
  )

region_usage_pct <- regions_used %>%
  left_join(regions_available, by = "year") %>%
  mutate(
    pct_used = (regions_used / regions_available) * 100
  )


shark_region_usage <- df_mb %>%
  mutate(year = year(DateTime)) %>%     # or year(date) if your column is named 'date'
  group_by(Transmitter_ID, year) %>%
  summarise(regions_used = n_distinct(Site.GroupName), .groups = "drop")

shark_region_usage_pct <- shark_region_usage %>%
  left_join(regions_available, by = "year") %>%
  mutate(pct_used = (regions_used / regions_available) * 100)

shark_region_usage_pct %>% 
  group_by(year) %>% 
  filter(year != 2021) %>%
  summarize(average_pct_node_useage = mean(pct_used),
            n = n())

shark_region_usage_pct %>% 
  filter(year == 2025)
```

# General Monterey Bay Map Plotting
```{r fig.height = 5, fig.width=5, dpi=150}
library(terra)
library(stars)
library(ggplot2)
library(sf)
#library(cowplot)   # for plot_grid or theme
library(ggspatial) # for north arrow, scale bar (optional)
library(rnaturalearth)

bm <- './etopo_bedrock.tiff'
bathy <- rast(bm)

# zoom extent (Monterey Bay)
xlim <- c(-122.3, -121.7)
ylim <- c(36.4, 37.1)

# crop bathy
bathy_crop <- crop(bathy, ext(xlim[1], xlim[2], ylim[1], ylim[2]))

bathy_ocean <- ifel(bathy_crop < -1, bathy_crop, NA)
bathy_stars <- st_as_stars(bathy_ocean)
coast <- ne_coastline(scale = "medium", returnclass = "sf")

# depth limits
depth_limits <- terra::minmax(bathy_ocean)

ggplot() +
  geom_stars(data = bathy_stars) +
  scale_fill_gradientn(
    colours = rev(RColorBrewer::brewer.pal(9, "Blues")),
    na.value = "darkgrey",
    values = scales::rescale(c(-200, -50, 0)),
    name = "Depth (m)"
  ) +
  coord_sf(xlim = xlim, ylim = ylim, expand = FALSE) +
  theme_minimal() +
  theme(
    axis.title = element_blank(),
    axis.text = element_text(size = 10),
    axis.ticks.length = unit(3, "pt"),
    panel.grid = element_blank()
  )
```
